version: '3.7'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: aleksizverev/yamdb:latest
    restart: always
    volumes: 
      - ./static_volume:/code/static/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.4
    restart: unless-stopped
    volumes:
      - ./static_volume:/code/static/
      - ./media:/media/
      - ./nginx/nginx.conf:/nginx/conf/nginx.conf/
    ports:
      - 80:80
    depends_on:
      - web
